version: "3.9"
services:
  task-tracker:
    image: task-tracker:1.0-SNAPSHOT
    ports:
      - "8081:8080"
    depends_on:
      - task-tracker-postgres
    environment:
      SPRING_CONFIG_LOCATION: /config/application.yaml
    volumes:
      - ./src/main/resources/application.yaml:/config/application.yaml
  task-tracker-postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: "task-tracker"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./schema/init.sql:/docker-entrypoint-init.db/init.sql